Attempt registry cache on Docker-Publish-Rootless

diff --git a/.github/workflows/docker-publish-rootless.yaml b/.github/workflows/docker-publish-rootless.yaml
--- a/.github/workflows/docker-publish-rootless.yaml
+++ b/.github/workflows/docker-publish-rootless.yaml
@@ -28,7 +28,6 @@ env:
   DOCKERHUB_REPO: sysadminsmedia/homebox
   GHCR_REPO: ghcr.io/sysadminsmedia/homebox
 
-
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -50,7 +49,7 @@ jobs:
       - name: Prepare
         run: |
           platform=${{ matrix.platform }}
-          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV          
+          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
 
       - name: Docker meta
         id: meta
@@ -58,7 +57,7 @@ jobs:
         with:
           images: |
             ${{ env.DOCKERHUB_REPO }}
-            ${{ env.GHCR_REPO }}            
+            ${{ env.GHCR_REPO }}
 
       - name: Login to Docker Hub
         uses: docker/login-action@v3
@@ -82,7 +81,14 @@ jobs:
         uses: docker/setup-buildx-action@v3
         with:
           driver-opts: |
-            image=ghcr.io/amitie10g/buildkit:master
+            image=ghcr.io/amitie10g/buildkit:latest
+          buildkitd-flags: "--build-arg BUILDKIT_INLINE_CACHE=1"
+
+      - name: Check for cache presence
+        id: cache_check
+        run: |
+          # Check if cache image exists, and skip pull if already present
+          docker pull ghcr.io/sysadminsmedia/devcache:homebox || echo "Cache not found, proceeding with build."
 
       - name: Build and push by digest
         id: build
@@ -91,14 +97,14 @@ jobs:
           platforms: ${{ matrix.platform }}
           labels: ${{ steps.meta.outputs.labels }}
           outputs: type=image,"name=${{ env.DOCKERHUB_REPO }},${{ env.GHCR_REPO }}",push-by-digest=true,name-canonical=true,push=true
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
+          cache-from: type=registry,ref=ghcr.io/sysadminsmedia/devcache:homebox
+          cache-to: type=registry,ref=ghcr.io/sysadminsmedia/devcache:homebox,mode=max
 
       - name: Export digest
         run: |
           mkdir -p /tmp/digests
           digest="${{ steps.build.outputs.digest }}"
-          touch "/tmp/digests/${digest#sha256:}"          
+          touch "/tmp/digests/${digest#sha256:}"
 
       - name: Upload digest
         uses: actions/upload-artifact@v4
@@ -144,7 +150,7 @@ jobs:
         uses: docker/setup-buildx-action@v3
         with:
           driver-opts: |
-            image=ghcr.io/amitie10g/buildkit:master
+            image=ghcr.io/amitie10g/buildkit:latest
 
       - name: Docker meta
         id: meta
@@ -169,7 +175,7 @@ jobs:
           docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
             $(printf '${{ env.DOCKERHUB_REPO }}@sha256:%s ' *)
           docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
-            $(printf '${{ env.GHCR_REPO }}@sha256:%s ' *)          
+            $(printf '${{ env.GHCR_REPO }}@sha256:%s ' *)
 
       - name: Inspect image
         run: |
